[project]
name = "pankegg"
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64"]

[dependencies]
python = ">=3.8"
flask = "==3.1.1"
pandas = "==2.2.3"
numpy = "==2.2.6"
scikit-learn = "==1.6.1"
scipy = "==1.15.2"
jinja2 = "==3.1.6"
click = "==8.2.1"
pytest = "==8.4.0"
pip = "==25.1.1"
importlib-metadata = "==8.7.0"
